table Data
	lineageTag: c0cc0a14-0afa-4f59-98c7-9d836e36fe4a

	column Date
		dataType: string
		lineageTag: 8a65a38e-510b-48e6-b3bf-363519e787e8
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column 'Business Area'
		dataType: string
		lineageTag: 75782671-cdf7-4071-86bc-4b5694f54bda
		summarizeBy: none
		sourceColumn: Business Area

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 3712d9f1-3cd3-46e5-967c-bd45dce206fb
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 6f8768ba-2d34-4eff-978e-2bbd0687cca0
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column 'IT Sub Area'
		dataType: string
		lineageTag: 0bac022e-9039-4527-893c-2ff85f82f14d
		summarizeBy: none
		sourceColumn: IT Sub Area

		annotation SummarizationSetBy = Automatic

	column 'IT Area'
		dataType: string
		lineageTag: 9304983c-78e9-4e2b-8d04-ad8205605a54
		summarizeBy: none
		sourceColumn: IT Area

		annotation SummarizationSetBy = Automatic

	column 'Cost element name'
		dataType: string
		lineageTag: 720fa31a-dc19-4a86-a762-4f500f1aeb35
		summarizeBy: none
		sourceColumn: Cost element name

		annotation SummarizationSetBy = Automatic

	column 'Cost Element Group'
		dataType: string
		lineageTag: 5d3b6800-417e-449a-be0f-d2d02e045fe6
		summarizeBy: none
		sourceColumn: Cost Element Group

		annotation SummarizationSetBy = Automatic

	column 'Cost Element Sub Group'
		dataType: string
		lineageTag: c5f83060-afeb-45e7-b282-c55acd8b418f
		summarizeBy: none
		sourceColumn: Cost Element Sub Group

		annotation SummarizationSetBy = Automatic

	column Actual
		dataType: double
		lineageTag: 2aa1728b-4c4e-43a1-a3fc-49dd34a4ab02
		summarizeBy: sum
		sourceColumn: Actual

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Forecast
		dataType: double
		lineageTag: db71b0bd-b89a-4bd4-8ee4-93d24e97b1fa
		summarizeBy: sum
		sourceColumn: Forecast

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Plan
		dataType: double
		lineageTag: 6e63bac1-04c4-4ea8-bc39-7ad5a1af7868
		summarizeBy: sum
		sourceColumn: Plan

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Data = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Chaitali\Downloads\IT Expenditure dataset.xlsx"), null, true),
				    Data_Sheet = Source{[Item="Data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Data_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type text}, {"Business Area", type text}, {"Region", type text}, {"Country", type text}, {"IT Sub Area", type text}, {"IT Area", type text}, {"Cost element name", type text}, {"Cost Element Group", type text}, {"Cost Element Sub Group", type text}, {"Actual", type number}, {"Forecast", type number}, {"Plan", type number}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type")
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

